import { getProviders, signIn } from 'next-auth/react'
import Head from 'next/head'
import cn from 'classnames'
export async function getServerSideProps() {
  const providers = await getProviders()
  return {
    props: { providers },
  }
}

function login({ providers }) {
  let socialBtn = providerId => {
    let className
    switch (providerId) {
      case 'facebook':
        className = 'btn-info'
        break
      case 'github':
        className = 'bg-gray-800'
        break
      case 'google':
        className = 'btn-error'
        break
      default:
        className = 'btn-primary'
        break
    }
    return className
  }

  return (
    <div className='min-h-screen flex flex-1 flex-col p-2 items-center justify-center '>
      <Head>
        <title>Signing in</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <link
          rel='icon'
          href='/favicon.ico'
        />
      </Head>

      <div className='flex w-full flex-1 flex-col items-center justify-around px-5'>
        <div className='card w-full md:w-2/3 lg:w-1/2 bg-black text-neutral-content'>
          <div className='card-body'>
            <div className='card-title font-bold text-2xl justify-center uppercase pb-5'>
              Sign in option
            </div>
            <div className='card-actions gap-3'>
              {Object.values(providers).map(provider => (
                <button
                  key={provider.name}
                  className={cn(
                    'btn btn-block transition-opacity hover:opacity-70',
                    socialBtn(provider.id)
                  )}
                  onClick={() => signIn(provider.id)}
                >
                  Login with {provider.name}
                </button>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

export default login
