import Head from 'next/head'
import ListOfCards from '../components/home/ListOfCards'
import Navbar from '../components/home/Navbar'

export default function Home() {
  return (
    <>
      <Head>
        <title>Memory Note</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <link
          rel='icon'
          href='/favicon.ico'
        />
      </Head>
      <Navbar />
      <main className='flex w-full flex-1 flex-col items-center justify-start text-center p-10'>
        <ListOfCards className={'flex flex-1 justify-start flex-col w-full'} />
      </main>
    </>
  )
}

