import Head from 'next/head'
import GenerateCardsInput from '../components/home/GenerateCardsInput.jsx'
import ListOfCards from '../components/home/ListOfCards'
import Welcome from '../components/home/Welcome.jsx'

export default function Home() {
  return (
    <div className='flex min-h-screen flex-col items-center justify-center p-2'>
      <Head>
        <title>Memory Note</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <link
          rel='icon'
          href='/favicon.ico'
        />
      </Head>

      <main className='flex w-full flex-1 flex-col items-stretch justify-start py-10 lg:px-20 text-center'>
        <Welcome className={'font-bold text-2xl py-10 lg:py-5'} />
        <GenerateCardsInput className={'flex justify-center py-10 lg:py-5'} />
        <ListOfCards className={'flex flex-1 justify-start flex-col'} />
      </main>
    </div>
  )
}

